setw -g mode-keys vi

# remap prefix from 'C-b'
unbind C-b
set-option -g prefix C-a 
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


# Swap pannels
bind > swap-pane -D # swap current pane with the next one
bind < swap-pane -U # swap current pane with the previous one

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2


# Powerline look
tmux_conf_theme_left_separator_main='\uE0B0'
tmux_conf_theme_left_separator_sub='\uE0B1'
tmux_conf_theme_right_separator_main='\uE0B2'
tmux_conf_theme_right_separator_sub='\uE0B3'

#set -g default-terminal "screen-256color"

#copy/Paste
bind p paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Removing the pain
unbind-key C-o

set -g status off

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256scr*:Tc"
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
run -b '~/.tmux/plugins/tpm/tpm'
